[project]
name = "runw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
runw = "runw.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
